name: Push heroku

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Clone repository
        run: |
          git clone https://slow:${{ secrets.GH_TOKEN }}@github.com/slow/nitro-sniper
          cd nitro-sniper

      - name: Delete workflows
        run: |
          cd ".github"
          rm -rf workflows
          cd ..

      - name: Set up credentials
        run: |
          git config --global user.name 'eternal'
          git config --global user.email '73202350+slow@users.noreply.github.com'

      - name: Commit changes
        run: |
          git add .
          git commit -m "Delete workflows and release"

      - name: Change remote to alternate repository
        run: |
          git remote set-url origin https://slow:${{ secrets.GH_TOKEN }}@github.com/slow/nitro-sniper-heroku
          
      - name: Forcefully push to the new origin
        run: |
          git push --force