name: Release

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Commit to nitro-sniper-heroku
        run: |
          git clone https://slow:$GITHUB_TOKEN@github.com/slow/nitro-sniper
          cd nitro-sniper

          git config --global user.name 'eternal'
          git config --global user.email '73202350+slow@users.noreply.github.com'

          git remote set-url origin https://slow:$GITHUB_TOKEN@github.com/slow/nitro-sniper-heroku

          git push --force