name: Release

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:      
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.GH_TOKEN }}
        with:
          source-directory: './'
          destination-github-username: 'slow'
          destination-repository-name: 'nitro-sniper-heroku'
          user-email: 73202350+slow@users.noreply.github.com
          target-branch: main

name: Merge upstream branches
on:
  push:
    branches: [ main ]

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge upstream
        run: |
          git clone https://slow:$GITHUB_TOKEN@github.com/slow/nitro-sniper
          cd nitro-sniper

          git config --global user.name 'eternal'
          git config --global user.email '73202350+slow@users.noreply.github.com'

          git remote set-url origin https://slow:$GITHUB_TOKEN@github.com/slow/nitro-sniper-heroku

          git push --force